В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [78]:
import numpy as np

In [79]:
# 1
def sigmoid(z):
    return 1 / (1 + np.e ** -z)

In [80]:
# 2
Z = np.array([-2, -1, 0, 1, 2])
sigmoid(Z)

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [81]:
def hypothisis(theta, X):
    # z = np.dot(theta, X)
    # так як множимо всвю матрицю X одразу 
    z = np.dot(X, theta)
    return sigmoid(z)

In [82]:
theta = np.array([0.5, -0.5])
X = np.array([[1, 2],
               [1, -1],
               [1, 0],
               [1, 1]])


In [83]:
hypothisis(theta, X)

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [84]:
theta = np.array([0.5, -0.5])

X = np.array([[1, 2],
              [1, -1],
              [1, 0],
              [1, 1]])

Y = np.array([1, 0, 1, 0])

In [85]:
# кожний приклад обробляється окремо
# def compute_gradient1(theta, X, Y):
#     m = len(X)
#     grads = np.zeros(len(X[0]))
#     # j - індекс змінної
#     for j in range(len(X[0])):
#         # i - індекс прикладу
#         sum = 0
#         for i in range(len(X)):
#             error = (hypothisis(theta, X[i]) - Y[i])
#             if j == 0:
#                 sum += error
#             else: 
#                 sum += error * X[i][j]
#         grads[j] = (1/m) * sum
#     return grads

In [86]:
# compute_gradient1(theta, X, Y)

In [87]:
def compute_gradient(theta, X, Y):

    m = len(X)

    intercept = (1/m) * np.sum(hypothisis(theta, X) - Y)
    coef = (1/m) * np.sum((hypothisis(theta, X) - Y) * X.T[1])

    return np.array([intercept, coef])


In [88]:
compute_gradient(theta, X, Y)

array([ 0.05776464, -0.36899431])


#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [89]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    
    m, n = X.shape
    theta = np.zeros(n)
    # theta = np.array([0.5, -0.5])

    for _ in range(epochs):

        pred = hypothisis(theta, X)
        theta -= lr * compute_gradient(theta, X, y)

    return theta

In [90]:
theta_fbgd = full_batch_gradient_descent(X, Y, lr = 0.001, epochs=1000)
print(f'Отримані параметри тета: {theta_fbgd}')


Отримані параметри тета: [-0.01264989  0.20921594]


#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [91]:
# 1
def predict_proba(x): 
    return hypothisis(theta_fbgd, x)

# 2
def predict(X, threshold=0.5):

    preds = predict_proba(X)
    classify = lambda x: 0 if x < threshold else 1
    predicted_classes = np.array([classify(p) for p in preds])

    return predicted_classes

# 3
def accuracy(y_true, y_pred):
    comp = (y_true == y_pred).astype(int)
    sum = np.sum(comp)
    return sum/len(comp)

In [92]:
# 4
pred  = [predict_proba(x) for x in X]
predicted_classes = predict(X)
acc = accuracy(Y, predicted_classes)
print(f'Передбачені моделлю імовірності: {pred}\nПередбачені класи кожного екземпляра: {predicted_classes}\nСправжні класи кожного екземпляра: {Y}\nТочність моделі: {acc}')

Передбачені моделлю імовірності: [0.6000760501148588, 0.4447599539535031, 0.4968375702510628, 0.5489838938736514]
Передбачені класи кожного екземпляра: [1 0 0 1]
Справжні класи кожного екземпляра: [1 0 1 0]
Точність моделі: 0.5
