### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [137]:
import numpy as np

In [138]:
vector = np.random.rand(10)
vector

array([0.94583025, 0.53777109, 0.33997908, 0.31611023, 0.64781145,
       0.03033062, 0.40076077, 0.10810653, 0.580338  , 0.82554803])

In [139]:
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [140]:
vector = np.round(vector + 10, 2)
vector

array([10.95, 10.54, 10.34, 10.32, 10.65, 10.03, 10.4 , 10.11, 10.58,
       10.83])

In [141]:
matrix = matrix * 2
matrix

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [142]:
vector_sqr = vector * vector
vector_sqr

array([119.9025, 111.0916, 106.9156, 106.5024, 113.4225, 100.6009,
       108.16  , 102.2121, 111.9364, 117.2889])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [143]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [144]:
# 1
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [145]:
# 2
# result_matrix - 2х2
# C - 2х1
# В результаті маємо отрмати матрицю 2х1
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [146]:
# 3
# result_matrix - 2х2
# D - 2х2
# В результаті маємо отрмати матрицю 2х2
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [147]:
# 1
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [148]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [149]:
# 2
vector, vector.shape

(array([10.95, 10.54, 10.34, 10.32, 10.65, 10.03, 10.4 , 10.11, 10.58,
        10.83]),
 (10,))

In [150]:
vector.T, vector.T.shape

(array([10.95, 10.54, 10.34, 10.32, 10.65, 10.03, 10.4 , 10.11, 10.58,
        10.83]),
 (10,))

In [151]:
# 3
column_vector = np.expand_dims(vector, axis=1)
column_vector


array([[10.95],
       [10.54],
       [10.34],
       [10.32],
       [10.65],
       [10.03],
       [10.4 ],
       [10.11],
       [10.58],
       [10.83]])

In [152]:
vector.shape, column_vector.shape

((10,), (10, 1))

In [153]:
# 4
column_vector.T, column_vector.T.shape

(array([[10.95, 10.54, 10.34, 10.32, 10.65, 10.03, 10.4 , 10.11, 10.58,
         10.83]]),
 (1, 10))